### ISSUE TITLE
ATECC608 support?

### ISSUE THREAD

**Issue by torntrousers** [earlephilhower/bearssl-esp8266#18]
Hi, thanks for all your ESP8266 work.  I'd like to use a [MicroChip ATECC608A](https://ww1.microchip.com/downloads/en/DeviceDoc/ATECC608A-CryptoAuthentication-Device-Summary-Data-Sheet-DS40001977B.pdf) secure element with an ESP8266 having the TLS client private key come from the ATECC608A. It doesn't look like thats support yet in this library, is it? It is supportted in the [Arduino BearSSL](https://github.com/arduino-libraries/ArduinoBearSSL) library so should be possible, any idea how hard that might be to get to work?

**Comment by earlephilhower** [comment]
Sorry, I don't have any boards with an included security chip so it's not likely to be done, and the Arduino folks sadly didn't get an upstream PR to have it included in base BearSSL.

Theoretically, you just need to introduce a set of functions w/the same signature as the existing encryption ones but which just send data to/from the ATECC chip instead of really doing math on the 8266.  The BSSL docs explicitly mention something like that.  If you do hack something out, definitely send a PR!  We can then see if the main BSSL author would be interested in it, too.

Good luck!
