### ISSUE TITLE
BearSSL can use for Arduino ESP32 platform too?

### ISSUE THREAD

**Issue by TridentTD** [earlephilhower/bearssl-esp8266#3]
BearSSL for Arduino ESP8266 is cool ssl-connection without fingerprint/Cert.
I wish to have Arduino BearSSL's library for ESP32 too.
Do you mind to port for ESP32?

Sorry for my poor English.
Thank you.

**Comment by earlephilhower** [comment]
Sorry, I don't do much for the ESP32 other than minor testing of the ESP8266Audio libraries.

That said, the ESP32 probably has enough RAM that you don't need the changes I did to make it work in the 40KB available on the ESP8266.  A lot of the changes were related to the small stack on the 8266 (<4KB available), something I think the ESP32 doesn't have a problem with.

I would recommend just going to the [BearSSL website](https://www.bearssl.org) and just cloning and compiling it and seeing how it goes.  

Once it's compiled, if you are using the Arduino core you can check the esp8266 Arduino sources for the WiFiClientSecure implementation as a starting point.  Otherwise, the examples in the BearSSL tree are a good starting point.

**Comment by letswebtech** [comment]
@TridentTD , Did you find the solution for this. Please share the approach or your solution to this problem.
Thank you

**Comment by yknivag** [comment]
@letswebtech @TridentTD I'd like to know if anyone has managed this too. If you've managed to solve this then please do update here as I'm sure there must be others wanting to know too.
